import { NextResponse } from "next/server"
import { ensureSeeded, getCase, getInvestigation, getScenarioForCase, listAlerts, listEvidence, appendEvidence } from "@/lib/store"
import { requireRole } from "@/lib/api/session"
import { PERMISSIONS } from "@/lib/auth"
import { verifyChain } from "@/lib/evidence/evidence"
import { getRepository } from "@/lib/db"

// Assembles a full investigation report payload (JSON). The frontend renders /
// exports it. Includes the evidence hash + chain-integrity check.
export async function GET(_req: Request, { params }: { params: Promise<{ id: string }> }) {
  await ensureSeeded()
  const auth = await requireRole(PERMISSIONS.exportReport)
  if ("response" in auth) return auth.response
  const { id } = await params
  const c = getCase(id)
  if (!c) return NextResponse.json({ error: "Case not found." }, { status: 404 })
  const investigation = getInvestigation(id)
  if (!investigation) {
    return NextResponse.json({ error: "Run the investigation before generating a report." }, { status: 409 })
  }
  const scenario = getScenarioForCase(id)
  const evidence = listEvidence(id)
  const integrity = verifyChain(evidence)
  const latestHash = evidence.length ? evidence[evidence.length - 1].contentHash : null

  const report = {
    generatedAt: new Date().toISOString(),
    generatedBy: auth.user.name,
    disclaimer:
      "This report is investigative decision-support. All exchange/VASP attributions are PROBABLE unless independently verified. TRACECHAIN AI performs no automatic legal action or asset freezing.",
    caseInformation: {
      id: c.id,
      title: c.title,
      complaintRef: c.complaintRef,
      status: c.status,
      investigator: c.investigator,
      createdAt: c.createdAt,
      updatedAt: c.updatedAt,
      provenance: c.provenance,
    },
    reportedWallet: { address: c.reportedWallet, chain: c.chain },
    investigationSummary: investigation.summary,
    fraudTypology: investigation.fraudprint.result,
    fundFlow: {
      graphNodes: scenario?.nodes.length ?? 0,
      graphEdges: scenario?.edges.length ?? 0,
      journey: investigation.journey,
    },
    suspiciousWallets: (scenario?.nodes ?? []).filter((n) => n.kind === "SUSPICIOUS").map((n) => n.id),
    burnerWallets: investigation.ghostWallet.result.burners,
    launderingAnalysis: investigation.laundering.result,
    crossChainActivity: investigation.crossChain.result,
    vaspAttribution: investigation.exitPoint.result.exitPoints.map((e) => ({
      address: e.address,
      category: e.attribution.category,
      vasp: e.attribution.vasp?.name ?? null,
      inboundUsd: e.inboundValue,
    })),
    exitPointAi: investigation.exitPoint.result,
    fundDna: investigation.fundDna.result,
    recoveryAnalysis: investigation.recover.result,
    risk: investigation.risk.result,
    priorityScore: investigation.priorityScore,
    recommendations: investigation.actionPack.result,
    evidence: {
      records: evidence,
      chainIntegrity: integrity,
      latestHash,
      timestamp: new Date().toISOString(),
    },
  }

  await appendEvidence({
    caseId: id,
    type: "REPORT_GENERATED",
    title: "Investigation report generated",
    summary: `Report generated by ${auth.user.name}. Chain integrity: ${integrity.valid ? "VALID" : "BROKEN"}.`,
    content: { latestHash },
    createdBy: auth.user.name,
    provenance: "HEURISTIC_ANALYSIS",
  })

  // Persist the generated report and associate it with its investigation.
  // The report is generated on demand, so this is the point at which it is
  // persisted. It is best-effort: a persistence failure must not prevent the
  // investigator from viewing/downloading the report they just generated.
  let persistence: { mode: string; persisted: boolean } = {
    mode: "IN_MEMORY",
    persisted: false,
  }
  try {
    const repo = getRepository()
    await repo.init()
    // Ensure the investigation row exists (FK target) before writing the
    // report — idempotent upsert against the same in-memory case/result.
    await repo.saveInvestigation({
      case: c,
      investigation,
      alerts: listAlerts().filter((a) => a.caseId === id),
      evidence: listEvidence(id),
      userId: auth.user.id,
      actor: auth.user.name,
    })
    await repo.saveReport({ investigationId: id, generatedBy: auth.user.name, data: report })
    await repo.appendInvestigationEvent({
      investigationId: id,
      actor: auth.user.name,
      action: "REPORT_GENERATED",
      detail: `Investigation report generated and persisted (${repo.persistenceMode === "POSTGRES" ? "persistent database" : "in-memory store"}).`,
      metadata: { chainIntegrity: integrity.valid },
    })
    persistence = { mode: repo.persistenceMode, persisted: true }
  } catch (err) {
    console.log("[v0] Report persistence failed:", err instanceof Error ? err.message : err)
    persistence = { mode: getRepository().persistenceMode, persisted: false }
  }

  return NextResponse.json({ report, persistence })
}
